In [1]:
import pandas as pd
import requests
import matplotlib.pyplot as plt
import requests 

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [2]:
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})
df.head()

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [3]:
df.rename(columns={"entity": "Pais"}, inplace=True)

In [4]:
df.head(3)

          Pais code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138

In [5]:
df.rename(columns={"code": "Codigo"}, inplace=True)

In [6]:
df.rename(columns={"year": "Ano"}, inplace=True)

In [15]:
df.rename(columns={"life_expectancy_0": "expectativa de vida"}, inplace=True)

In [16]:
df.head(3)

          Pais Codigo   Ano  expectativa de vida
0  Afghanistan    AFG  1950              28.1563
1  Afghanistan    AFG  1951              28.5836
2  Afghanistan    AFG  1952              29.0138

In [ ]:
df.set_index("Pais","Ano", )

In [ ]:
df.loc[df{"Pais"}.str.contains("UNITED")]

In [ ]:
df.dropna(subset={"Codigo"})

In [17]:
resultado = (
    df.groupby("Pais")["expectativa de vida"]
    .mean()
    .sort_values(ascending=True)
)

In [18]:
resultado.head(3)

Pais
USSR            32.700000
South Sudan     37.841631
Sierra Leone    43.189605
Name: expectativa de vida, dtype: float64

In [28]:
resultado = (
    df.groupby("Pais")["Ano"]
    .mean()
    .sort_values(ascending=True)
)

In [26]:
resultado.head(3)

Pais
United Kingdom       1872.5
Sweden               1887.0
England and Wales    1895.0
Name: Ano, dtype: float64